add product crud
reznov46/wsei_backend pull request #13
Opened 2023-06-30 22:50 UTC by reznov46

2023-07-01 09:18 UTC, Hexagonale requested changes

2023-07-01 09:18 UTC, Hexagonale commented on .gitignore
> +elo.rest
Maybe `*.rest`?

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/dtos/productCreate.dto.ts
> +    @IsOptional()
Formatting

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/controller/products.controller.ts
> +	}
Make `@Delete(/:id)` this will eliminate DTOs and stuff

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/controller/products.controller.ts
> +	}
Make `@Patch(/:id)` this will eliminate DTOs and stuff

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/dtos/productUpdate.dto.ts
> +    @IsOptional()
Formatting

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/models/product.ts
> +
Constructor is not needed I guess

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/models/product.ts
> +	@Column({ name: 'is_deleted', type: 'boolean', default: () => '0' })
Spacing

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/models/product.ts
> +	@Column({ name: 'is_deleted', type: 'boolean', default: () => '0' })
And updated by is kind of useless because product can be updated many times and it stores only the last one

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/models/product.ts
> +	@Column({ name: 'is_deleted', type: 'boolean', default: () => '0' })
Same with updated at

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/models/product.ts
> +	public price?: number;
Why nullable?

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/models/product.ts
> +	public fullDescription?: string;
Why nullable? I guess full description could be nullable but I would leave description as required

2023-07-01 09:18 UTC, Hexagonale commented on backend/common/src/decorators/getUser.decorator.ts
> +    })
Format

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/controller/products.controller.ts
> +	}
This creates a little problem, comment this for now please. I will think of a solution

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/service/products.service.ts
Empty lines between the methods please

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/service/products.service.ts
> +		}
Empty line before, between and after ifs

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/service/products.service.ts
> +		const { name, description, fullDescription, price } = product;
Empty line after if

2023-07-01 09:18 UTC, Hexagonale commented on backend/athena/src/products/service/products.service.ts
> +		oldProduct.isDeleted = true;
Empty line

2023-07-03 20:28 UTC, reznov46 commented on backend/common/src/models/product.ts
> +	@Column({ name: 'is_deleted', type: 'boolean', default: () => '0' })
True, habbit from work lmao, we use mssql audit tables so it help a lot XD

2023-07-03 20:29 UTC, reznov46 commented on backend/common/src/models/product.ts
> +	@Column({ name: 'is_deleted', type: 'boolean', default: () => '0' })
I'll delete it

2023-07-03 21:25 UTC, reznov46 commented on backend/athena/src/products/controller/products.controller.ts
> +	}
How? We still need to pass parameters for the update

2023-07-03 21:28 UTC, reznov46 commented on backend/common/src/models/product.ts
> +	public fullDescription?: string;
I wouldn't, sometimes you just don't need a description of the product, the name says it all, and it's annoying for a customer to have to fill the filed with shit data like copy of the title

2023-07-05 15:39 UTC, merged